In [131]:
import numpy as np
import pandas as pd

In [132]:
n_simulations = 10_000

## Exercises

### 1. How likely is it that you roll doubles when rolling two dice?

In [133]:
outcomes = [1, 2, 3, 4, 5, 6]
# pips on a die

die1 = np.random.choice(outcomes, size=n_simulations)
die2 = np.random.choice(outcomes, size=n_simulations)
# creates the random dice rolls

In [134]:
(die1 == die2).mean()

0.1645

### 2. If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [135]:
outcomes = ['H', 'T']
# create outcomes for coin

n_trials = 8
# number of coins flipped

flips = np.random.choice(outcomes, size=(n_simulations, n_trials))
(np.count_nonzero(flips == 'H', axis=1) == 3).mean()
# ((counts number of Heads in each row) returns boolean if count = 3)

0.2246

In [339]:
(np.count_nonzero(flips == 'H', axis=1) > 3).mean()

0.6349

### 3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [341]:
outcomes = ['data', 'web']

n_trials = 2

drives = np.random.choice(outcomes, size=(n_simulations, n_trials), p=[.25, .75])
(np.count_nonzero(drives == 'data', axis=1) == 2).mean()

0.0628

In [342]:
(np.count_nonzero(drives == 'data', axis=1) == 1).mean()

0.3734

In [343]:
(np.count_nonzero(drives == 'data', axis=1) == 0).mean()

0.5638

### 4. Codeup students buy, on average, 3 poptart packages (+- 1.5) a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon?

In [370]:
mu = 3
# average of 3 poptarts a day

std_dev = 1.5
n_trials=5
#days

purchased_poptarts = np.random.normal(mu, std_dev, size=(n_simulations, n_trials))
# used random.normal since mean and stddev was already provided

In [371]:
purchased_poptarts

array([[ 0.71497956,  3.54531194,  4.50532773,  2.95544954,  3.27591727],
       [ 4.155248  ,  3.53179648,  1.9231011 ,  2.18360119,  0.94037781],
       [ 2.46040508,  2.84288116,  0.6843073 ,  3.77505035,  1.80277914],
       ...,
       [ 3.63259667,  0.30786615,  1.00958546,  3.46634593,  3.09907338],
       [ 3.5387938 ,  3.2931104 , -1.19286628,  2.77015017,  5.53700326],
       [ 1.09060789,  3.3664174 ,  0.74690887,  5.65161897,  3.19886722]])

In [372]:
weekly_poptarts = purchased_poptarts.sum(axis=1).astype(int)
# summed the total number of poptarts purchased within the simulated weeks

In [373]:
(weekly_poptarts <= 16).mean()
# (returns True for simulated weeks where 16 or less poptarts were purchased)

0.7283

### 5. Compare Heights:

Men have an average height of 178 cm and standard deviation of 8cm.

In [144]:
men_mu = 178
men_stddev = 8
# cm

Women have a mean of 170, sd = 6cm.

In [145]:
women_mu = 170
women_stddev = 6
# cm

In [146]:
random_man = np.random.normal(men_mu, men_stddev, n_simulations)

In [147]:
random_woman = np.random.normal(women_mu, women_stddev, n_simulations)

If a man and woman are chosen at random, P(woman taller than man)?

In [148]:
random_man < random_woman

array([ True, False, False, ..., False, False,  True])

In [149]:
(random_man < random_woman).mean()

0.2136

### 6. When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

In [380]:
prob = 1/250

In [381]:
outcomes = ['Pass', 'Fail']
(np.random.choice(outcomes, size=50, p=[249/250, 1/250]) == 'Pass').mean()
# For 50 students, ther probability of a all successful downloads is almost 100%

0.98

In [382]:
(np.random.choice(outcomes, size=100, p=[249/250, 1/250]) == 'Pass').mean()

0.99

What is the probability that we observe an installation issue within the first 150 students that download anaconda?

In [383]:
(np.random.choice(outcomes, size=150, p=[249/250, 1/250]) == 'Fail').mean()

0.0

How likely is it that 450 students all download anaconda without an issue?

In [384]:
(np.random.choice(outcomes, size=450, p=[249/250, 1/250]) == 'Pass').mean()
# For 450 students, ther probability of a all successful downloads is about 99%

0.9911111111111112

### 7. There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

In [155]:
outcomes = ['foodtruck', 'nothing']

In [156]:
np.random.choice(outcomes, size=(10_000, 3), p=[.7, 0.3])

array([['foodtruck', 'foodtruck', 'nothing'],
       ['foodtruck', 'nothing', 'nothing'],
       ['foodtruck', 'foodtruck', 'foodtruck'],
       ...,
       ['foodtruck', 'foodtruck', 'nothing'],
       ['foodtruck', 'foodtruck', 'foodtruck'],
       ['foodtruck', 'foodtruck', 'foodtruck']], dtype='<U9')

In [160]:
sightings = (np.random.choice(outcomes, size=(10_000, 3), p=[.7, 0.3]))

In [161]:
(np.count_nonzero(sightings == 'nothing', axis=1) == 3).mean()

0.0297

#### How likely is it that a food truck will show up sometime this week?

Assuming the week starts on Sunday and the remaining days are Wednesday through Saturday:

In [169]:
remaining_sightings = (np.random.choice(outcomes, size=(10_000, 4), p=[.7, 0.3]))
#change shape to 10000x4 to resemble remaining days of the week 

In [170]:
remaining_sightings

array([['foodtruck', 'nothing', 'foodtruck', 'foodtruck'],
       ['foodtruck', 'foodtruck', 'foodtruck', 'foodtruck'],
       ['foodtruck', 'foodtruck', 'foodtruck', 'foodtruck'],
       ...,
       ['foodtruck', 'foodtruck', 'foodtruck', 'foodtruck'],
       ['foodtruck', 'nothing', 'foodtruck', 'foodtruck'],
       ['nothing', 'nothing', 'foodtruck', 'foodtruck']], dtype='<U9')

In [171]:
(np.count_nonzero(remaining_sightings == 'foodtruck', axis=1) >= 1).mean()
# (returns True if foodtruck appears at least once in the week/row)

0.9905

### 8. If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?

In [204]:
outcomes = range(1, 357)

In [323]:
bday_array = np.random.choice(outcomes, size=(6, 23))

In [324]:
bday_array

array([[340, 198, 307, 168, 214, 314, 209, 270, 342, 257, 114,  74,  56,
         29, 287, 132, 162, 276, 179, 265, 279, 184, 252],
       [232,  68, 147, 130, 197, 270, 256, 182,  79, 127,  55, 271, 333,
        104,  22, 239,  68, 179,   9, 278,  69, 205, 281],
       [292, 188, 251, 293, 135, 124,  10, 159, 211, 240, 228,   3, 105,
        298, 156, 312, 264,  11,  79,  47, 134, 155, 174],
       [287, 245, 152,  83,  59, 227,  30, 152, 255,  21, 148, 150, 174,
         97, 263, 138,  15, 111, 245,  79, 256, 281, 131],
       [161, 353,  60, 121, 156, 314, 215, 156, 335, 232,  15, 269,   3,
        154,  83,   6, 136, 295,  23, 114,   2, 292, 114],
       [114, 184, 125, 114, 306, 140, 256, 250, 331, 347,  88,   8, 235,
        298, 331,  46, 286, 281,   7,  46,  48, 221, 159]])

In [327]:
x = np.sort(bday_array, axis=1)

In [337]:
bday_array.apply(lambda row: row.unique, axis=1)

AttributeError: 'numpy.ndarray' object has no attribute 'apply'

In [331]:
y = x.apply(lambda row: np.unique(row))

AttributeError: 'numpy.ndarray' object has no attribute 'apply'